dist: xenial
language: php
sudo: false

env:
  global:
    - COMPOSER_FLAGS="--prefer-stable"

matrix:
  include:
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
    - php: 7.3
    - php: 7.4
    - php: 7.4
      # This empty flag removes the prefer-stable switch to cause dev dependencies to be installed
      env: COMPOSER_FLAGS=""
    - php: nightly
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer self-update

before_script:
  - travis_retry composer update $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit
